### ISSUE TITLE
Investigate question solve not showing all the people involved

### ISSUE THREAD

**Issue by ghostdevv** [sveltejs/discord-bot#45]

**Comment by ardentkilnfire** [comment]
Probably because of [this](https://github.com/sveltejs/discord-bot/blob/6d8de69c80528938446ea8e99568a50d2ac8bbea/src/commands/questions/question.ts#L148)

because, `ActionRowBuilder` can only have 5 buttons or 1 select menu per row and 5 rows can be assigned as components

so when we map over `clickable_participants`, if there are more than 5 participants, it adds more than 5 buttons to the row (which is technically not the issue), but when we assign that row with more than 5 buttons errors out , thus not shwoing all the participants

I can open a PR to fix this, if you want :)

**Comment by ghostdevv** [comment]
Good catch @ardentkilnfire - would love a pr!

**Comment by ardentkilnfire** [comment]
alright, working on it :smile:
